### ISSUE TITLE
prometheus基本使用

### ISSUE THREAD

**Issue by yyt030** [yyt030/blog#4]
### 下载
从prometheus[官网](https://prometheus.io/download/)上下载最新的版本，解压
```bash
tar -xf prometheus-2.0.0.linux-amd64.tar.gz
cd prometheus-*
```
### 配置
prometheus是完整的监控产品，它通过http的方式收集指标，它也可以监控自身的指标数据。
配置job和每个job要收集的目标metric数据，配置文件分两级job、target，在k8sz中监控主要配置api-server和etcd的metric地址；
编辑prometheus.yml配置文件，具体如下：
```yaml
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['192.168.56.3:9090']
  - job_name: 'kubernetes'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.4:8080']
  - job_name: 'etcd-server'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.4:2379','192.168.56.5:2379','192.168.56.6:2379']
```
### 启动prometheus
```bash
./prometheus --config.file=prometheus.yml
```
然后就可以通过http://<ip>:9090访问
> 建议通过systemd服务启动prometheus

```bash
# /etc/systemd/system/prometheus.service
[Unit]
Description=prometheus
After=network.target
[Service]
Type=simple
#User=prometheus
ExecStart=/root/prometheus-2.0.0.linux-amd64/prometheus --config.file=/root/prometheus-2.0.0.linux-amd64/prometheus.yml --storage.tsdb.path=/var/lib/prometheus
Restart=on-failure
[Install]
WantedBy=multi-user.target
```
启动prometheus
`systemctl start prometheus`

### 监控prometheus服务器
为收集监控服务器上的CPU、内存、磁盘、io等信息，要安装node-exporter，该exporter的作用是收集机器系统数据，充当agent的作用；
- 安装node_exporter
- 配置node_exporter service文件
```file
# /etc/systemd/system/node_exporter.service
[Unit]
Description=node_exporter
After=network.target
[Service]
Type=simple
#User=prometheus
ExecStart=/root/prometheus-2.0.0.linux-amd64/node_exporter-0.15.2.linux-amd64/node_exporter
Restart=on-failure
[Install]
WantedBy=multi-user.target
```
- 启动node_exporter
```bash
systemctl start node_exporter
```
### 添加prometheus yaml文件中的监控点
```yaml
- job_name: 'linux'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
```
### 重启prometheus
```bash
systemctl restart prometheus
```

### 绘图展示
prometheus自带的监控界面比较简单，可以配合go实现的开源grafana，界面功能强大，美观；
```bash
docker run -d --name=grafana -p 3000:3000 grafana/grafana
```
> 通过http://<ip>:3000访问grafana,缺省帐号/密码为admin/admin
